// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg2f9P2JV90tUDLxv429OCa9tM7bFyiBQ',
    appId: '1:509265018986:web:4ab5172242bf2a49230a13',
    messagingSenderId: '509265018986',
    projectId: 'techsolutions-eb89a',
    authDomain: 'techsolutions-eb89a.firebaseapp.com',
    storageBucket: 'techsolutions-eb89a.firebasestorage.app',
    measurementId: 'G-36ZN1MGMF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdSjW4fTl8mrIIcpadqJosYwbsn_9b1Yc',
    appId: '1:509265018986:android:d77e08718d14cc61230a13',
    messagingSenderId: '509265018986',
    projectId: 'techsolutions-eb89a',
    storageBucket: 'techsolutions-eb89a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuZej_XN42PsONGMC9WHCBTC1IyCSBPJM',
    appId: '1:509265018986:ios:860b498ad7ba9291230a13',
    messagingSenderId: '509265018986',
    projectId: 'techsolutions-eb89a',
    storageBucket: 'techsolutions-eb89a.firebasestorage.app',
    androidClientId: '509265018986-ldf7e5qtu9eisnme25i4lva5b2km95qg.apps.googleusercontent.com',
    iosClientId: '509265018986-nbn7047ct4rb77hhlj2beqna2d6lq64d.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuZej_XN42PsONGMC9WHCBTC1IyCSBPJM',
    appId: '1:509265018986:ios:860b498ad7ba9291230a13',
    messagingSenderId: '509265018986',
    projectId: 'techsolutions-eb89a',
    storageBucket: 'techsolutions-eb89a.firebasestorage.app',
    androidClientId: '509265018986-ldf7e5qtu9eisnme25i4lva5b2km95qg.apps.googleusercontent.com',
    iosClientId: '509265018986-nbn7047ct4rb77hhlj2beqna2d6lq64d.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg2f9P2JV90tUDLxv429OCa9tM7bFyiBQ',
    appId: '1:509265018986:web:18cceb15881748f6230a13',
    messagingSenderId: '509265018986',
    projectId: 'techsolutions-eb89a',
    authDomain: 'techsolutions-eb89a.firebaseapp.com',
    storageBucket: 'techsolutions-eb89a.firebasestorage.app',
    measurementId: 'G-98PSFWN3P2',
  );
}
